import { DataSource } from 'typeorm';
import { University, UniversityType, UniversityStatus } from '../entities/university.entity';
import { UniversityReviewCriterion, CriterionType, CriterionWeight } from '../entities/university-review-criterion.entity';

export class UniversitySeeder {
  constructor(private dataSource: DataSource) {}

  async run() {
    console.log('🌱 Seeding universities and review criteria...');

    // Seed review criteria first
    await this.seedReviewCriteria();

    // Seed universities
    await this.seedUniversities();

    console.log('✅ University seeding completed!');
  }

  private async seedReviewCriteria() {
    const criterionRepository = this.dataSource.getRepository(UniversityReviewCriterion);

    const criteria = [
      // Academic criteria
      {
        name: 'academic_quality',
        display_name: 'Chất lượng đào tạo',
        description: 'Đánh giá chất lượng giảng dạy, chương trình học và đội ngũ giảng viên',
        type: CriterionType.ACADEMIC,
        weight: CriterionWeight.CRITICAL,
        max_score: 5,
        is_active: true,
        is_required: true,
        sort_order: 1,
        icon: 'graduation-cap',
        color: '#3B82F6',
      },
      {
        name: 'curriculum',
        display_name: 'Chương trình đào tạo',
        description: 'Tính cập nhật và phù hợp của chương trình đào tạo',
        type: CriterionType.ACADEMIC,
        weight: CriterionWeight.HIGH,
        max_score: 5,
        is_active: true,
        is_required: true,
        sort_order: 2,
        icon: 'book-open',
        color: '#10B981',
      },
      {
        name: 'faculty_quality',
        display_name: 'Chất lượng giảng viên',
        description: 'Trình độ và kinh nghiệm của đội ngũ giảng viên',
        type: CriterionType.ACADEMIC,
        weight: CriterionWeight.HIGH,
        max_score: 5,
        is_active: true,
        is_required: true,
        sort_order: 3,
        icon: 'users',
        color: '#8B5CF6',
      },

      // Facility criteria
      {
        name: 'infrastructure',
        display_name: 'Cơ sở vật chất',
        description: 'Chất lượng phòng học, thư viện, phòng thí nghiệm',
        type: CriterionType.FACILITY,
        weight: CriterionWeight.HIGH,
        max_score: 5,
        is_active: true,
        is_required: true,
        sort_order: 4,
        icon: 'building',
        color: '#F59E0B',
      },
      {
        name: 'technology',
        display_name: 'Công nghệ và thiết bị',
        description: 'Mức độ hiện đại của công nghệ và thiết bị học tập',
        type: CriterionType.FACILITY,
        weight: CriterionWeight.MEDIUM,
        max_score: 5,
        is_active: true,
        is_required: false,
        sort_order: 5,
        icon: 'laptop',
        color: '#EF4444',
      },
      {
        name: 'accommodation',
        display_name: 'Ký túc xá',
        description: 'Chất lượng ký túc xá và dịch vụ sinh viên',
        type: CriterionType.FACILITY,
        weight: CriterionWeight.MEDIUM,
        max_score: 5,
        is_active: true,
        is_required: false,
        sort_order: 6,
        icon: 'home',
        color: '#06B6D4',
      },

      // Social criteria
      {
        name: 'student_life',
        display_name: 'Đời sống sinh viên',
        description: 'Hoạt động ngoại khóa, câu lạc bộ và sự kiện',
        type: CriterionType.SOCIAL,
        weight: CriterionWeight.MEDIUM,
        max_score: 5,
        is_active: true,
        is_required: false,
        sort_order: 7,
        icon: 'heart',
        color: '#EC4899',
      },
      {
        name: 'diversity',
        display_name: 'Đa dạng văn hóa',
        description: 'Môi trường đa dạng và hòa nhập',
        type: CriterionType.SOCIAL,
        weight: CriterionWeight.LOW,
        max_score: 5,
        is_active: true,
        is_required: false,
        sort_order: 8,
        icon: 'globe',
        color: '#84CC16',
      },

      // Career criteria
      {
        name: 'career_support',
        display_name: 'Hỗ trợ nghề nghiệp',
        description: 'Dịch vụ tư vấn nghề nghiệp và hỗ trợ việc làm',
        type: CriterionType.CAREER,
        weight: CriterionWeight.HIGH,
        max_score: 5,
        is_active: true,
        is_required: true,
        sort_order: 9,
        icon: 'briefcase',
        color: '#6366F1',
      },
      {
        name: 'internship_opportunities',
        display_name: 'Cơ hội thực tập',
        description: 'Chất lượng và số lượng cơ hội thực tập',
        type: CriterionType.CAREER,
        weight: CriterionWeight.MEDIUM,
        max_score: 5,
        is_active: true,
        is_required: false,
        sort_order: 10,
        icon: 'handshake',
        color: '#F97316',
      },
      {
        name: 'alumni_network',
        display_name: 'Mạng lưới cựu sinh viên',
        description: 'Sức mạnh và hoạt động của mạng lưới cựu sinh viên',
        type: CriterionType.CAREER,
        weight: CriterionWeight.MEDIUM,
        max_score: 5,
        is_active: true,
        is_required: false,
        sort_order: 11,
        icon: 'network-wired',
        color: '#A855F7',
      },

      // Overall criteria
      {
        name: 'overall_experience',
        display_name: 'Trải nghiệm tổng thể',
        description: 'Đánh giá tổng thể về trải nghiệm học tập',
        type: CriterionType.OVERALL,
        weight: CriterionWeight.CRITICAL,
        max_score: 5,
        is_active: true,
        is_required: true,
        sort_order: 12,
        icon: 'star',
        color: '#FCD34D',
      },
      {
        name: 'value_for_money',
        display_name: 'Giá trị đồng tiền',
        description: 'Mức độ hài lòng về chi phí học tập so với chất lượng nhận được',
        type: CriterionType.OVERALL,
        weight: CriterionWeight.HIGH,
        max_score: 5,
        is_active: true,
        is_required: true,
        sort_order: 13,
        icon: 'dollar-sign',
        color: '#22C55E',
      },
    ];

    for (const criterion of criteria) {
      const existingCriterion = await criterionRepository.findOne({
        where: { name: criterion.name },
      });

      if (!existingCriterion) {
        await criterionRepository.save(criterion);
        console.log(`✅ Created criterion: ${criterion.display_name}`);
      }
    }
  }

  private async seedUniversities() {
    const universityRepository = this.dataSource.getRepository(University);

    const universities = [
      {
        name: 'Đại học Bách khoa Hà Nội',
        short_name: 'BKHN',
        english_name: 'Hanoi University of Science and Technology',
        address: 'Số 1 Đại Cồ Việt, Hai Bà Trưng, Hà Nội',
        city: 'Hà Nội',
        province: 'Hà Nội',
        location: ['Hà Nội'],
        phone: '024 3869 4242',
        email: 'contact@hust.edu.vn',
        website: 'https://www.hust.edu.vn',
        facebook: 'https://www.facebook.com/dhbkhanoi',
        logo_url: 'https://example.com/bkhn-logo.png',
        banner_url: 'https://example.com/bkhn-banner.png',
        description: 'Đại học Bách khoa Hà Nội là một trong những trường đại học hàng đầu Việt Nam về kỹ thuật và công nghệ.',
        history: 'Được thành lập năm 1956, Đại học Bách khoa Hà Nội có lịch sử hơn 60 năm phát triển.',
        mission: 'Đào tạo nguồn nhân lực chất lượng cao trong lĩnh vực kỹ thuật và công nghệ.',
        vision: 'Trở thành trường đại học nghiên cứu hàng đầu khu vực châu Á.',
        type: UniversityType.PUBLIC,
        status: UniversityStatus.ACTIVE,
        founded_year: 1956,
        accreditation: 'AUN-QA',
        specializations: ['Kỹ thuật', 'Công nghệ', 'Kinh tế', 'Ngoại ngữ'],
        facilities: ['Thư viện', 'Phòng thí nghiệm', 'Ký túc xá', 'Sân thể thao'],
        achievements: ['Top 1000 thế giới', 'Top 10 Việt Nam'],
        ranking_national: 'Top 5',
        ranking_international: 'Top 1000',
        student_count: 45000,
        faculty_count: 1200,
        acceptance_rate: 15.5,
        tuition_fee_min: 15000000,
        tuition_fee_max: 25000000,
        currency: 'VND',
        admission_requirements: ['Tốt nghiệp THPT', 'Điểm thi THPT Quốc gia'],
        scholarships: ['Học bổng tài năng', 'Học bổng khuyến khích học tập'],
        international_partnerships: ['MIT', 'Stanford', 'Tokyo University'],
        campus_map_url: 'https://maps.google.com/?q=21.0074,105.8412',
        latitude: 21.0074,
        longitude: 105.8412,
        is_featured: true,
        is_verified: true,
        view_count: 15000,
        review_count: 1250,
        average_rating: 4.2,
        total_rating: 5250,
      },
      {
        name: 'Đại học Quốc gia Hà Nội',
        short_name: 'VNU',
        english_name: 'Vietnam National University, Hanoi',
        address: '144 Xuân Thủy, Cầu Giấy, Hà Nội',
        city: 'Hà Nội',
        province: 'Hà Nội',
        location: ['Hà Nội'],
        phone: '024 3754 7869',
        email: 'contact@vnu.edu.vn',
        website: 'https://www.vnu.edu.vn',
        facebook: 'https://www.facebook.com/vnuhanoi',
        logo_url: 'https://example.com/vnu-logo.png',
        banner_url: 'https://example.com/vnu-banner.png',
        description: 'Đại học Quốc gia Hà Nội là hệ thống đại học đa ngành hàng đầu Việt Nam.',
        history: 'Được thành lập năm 1993, VNU là sự kết hợp của các trường đại học hàng đầu Hà Nội.',
        mission: 'Đào tạo nguồn nhân lực chất lượng cao cho đất nước.',
        vision: 'Trở thành đại học nghiên cứu hàng đầu khu vực.',
        type: UniversityType.PUBLIC,
        status: UniversityStatus.ACTIVE,
        founded_year: 1993,
        accreditation: 'AUN-QA',
        specializations: ['Khoa học tự nhiên', 'Khoa học xã hội', 'Công nghệ', 'Y tế'],
        facilities: ['Thư viện', 'Phòng thí nghiệm', 'Bệnh viện', 'Trung tâm nghiên cứu'],
        achievements: ['Top 1000 thế giới', 'Top 3 Việt Nam'],
        ranking_national: 'Top 3',
        ranking_international: 'Top 1000',
        student_count: 50000,
        faculty_count: 1500,
        acceptance_rate: 12.0,
        tuition_fee_min: 12000000,
        tuition_fee_max: 20000000,
        currency: 'VND',
        admission_requirements: ['Tốt nghiệp THPT', 'Điểm thi THPT Quốc gia'],
        scholarships: ['Học bổng tài năng', 'Học bổng nghiên cứu'],
        international_partnerships: ['Harvard', 'Oxford', 'Tokyo University'],
        campus_map_url: 'https://maps.google.com/?q=21.0368,105.7821',
        latitude: 21.0368,
        longitude: 105.7821,
        is_featured: true,
        is_verified: true,
        view_count: 18000,
        review_count: 1450,
        average_rating: 4.3,
        total_rating: 6235,
      },
      {
        name: 'Đại học Bách khoa TP.HCM',
        short_name: 'BKHCM',
        english_name: 'Ho Chi Minh City University of Technology',
        address: '268 Lý Thường Kiệt, Quận 10, TP.HCM',
        city: 'TP.HCM',
        province: 'TP.HCM',
        location: ['TP.HCM'],
        phone: '028 3865 2222',
        email: 'contact@hcmut.edu.vn',
        website: 'https://www.hcmut.edu.vn',
        facebook: 'https://www.facebook.com/dhbkhcm',
        logo_url: 'https://example.com/bkhcm-logo.png',
        banner_url: 'https://example.com/bkhcm-banner.png',
        description: 'Đại học Bách khoa TP.HCM là trường đại học kỹ thuật hàng đầu miền Nam.',
        history: 'Được thành lập năm 1957, trường có lịch sử hơn 60 năm đào tạo kỹ sư.',
        mission: 'Đào tạo kỹ sư chất lượng cao cho khu vực miền Nam.',
        vision: 'Trở thành trường đại học kỹ thuật hàng đầu Việt Nam.',
        type: UniversityType.PUBLIC,
        status: UniversityStatus.ACTIVE,
        founded_year: 1957,
        accreditation: 'AUN-QA',
        specializations: ['Kỹ thuật', 'Công nghệ', 'Kinh tế', 'Kiến trúc'],
        facilities: ['Thư viện', 'Phòng thí nghiệm', 'Xưởng thực hành', 'Sân thể thao'],
        achievements: ['Top 1000 thế giới', 'Top 5 Việt Nam'],
        ranking_national: 'Top 5',
        ranking_international: 'Top 1000',
        student_count: 40000,
        faculty_count: 1000,
        acceptance_rate: 18.0,
        tuition_fee_min: 16000000,
        tuition_fee_max: 28000000,
        currency: 'VND',
        admission_requirements: ['Tốt nghiệp THPT', 'Điểm thi THPT Quốc gia'],
        scholarships: ['Học bổng tài năng', 'Học bổng khuyến khích học tập'],
        international_partnerships: ['MIT', 'Stanford', 'Tokyo Institute of Technology'],
        campus_map_url: 'https://maps.google.com/?q=10.7629,106.6602',
        latitude: 10.7629,
        longitude: 106.6602,
        is_featured: true,
        is_verified: true,
        view_count: 12000,
        review_count: 980,
        average_rating: 4.1,
        total_rating: 4018,
      },
      {
        name: 'Đại học Quốc gia TP.HCM',
        short_name: 'VNUHCM',
        english_name: 'Vietnam National University, Ho Chi Minh City',
        address: 'Linh Trung, Thủ Đức, TP.HCM',
        city: 'TP.HCM',
        province: 'TP.HCM',
        location: ['TP.HCM'],
        phone: '028 3724 4270',
        email: 'contact@vnuhcm.edu.vn',
        website: 'https://www.vnuhcm.edu.vn',
        facebook: 'https://www.facebook.com/vnuhcm',
        logo_url: 'https://example.com/vnuhcm-logo.png',
        banner_url: 'https://example.com/vnuhcm-banner.png',
        description: 'Đại học Quốc gia TP.HCM là hệ thống đại học đa ngành hàng đầu miền Nam.',
        history: 'Được thành lập năm 1995, VNUHCM là sự kết hợp của các trường đại học hàng đầu TP.HCM.',
        mission: 'Đào tạo nguồn nhân lực chất lượng cao cho khu vực miền Nam.',
        vision: 'Trở thành đại học nghiên cứu hàng đầu khu vực.',
        type: UniversityType.PUBLIC,
        status: UniversityStatus.ACTIVE,
        founded_year: 1995,
        accreditation: 'AUN-QA',
        specializations: ['Khoa học tự nhiên', 'Khoa học xã hội', 'Công nghệ', 'Y tế'],
        facilities: ['Thư viện', 'Phòng thí nghiệm', 'Bệnh viện', 'Trung tâm nghiên cứu'],
        achievements: ['Top 1000 thế giới', 'Top 4 Việt Nam'],
        ranking_national: 'Top 4',
        ranking_international: 'Top 1000',
        student_count: 48000,
        faculty_count: 1400,
        acceptance_rate: 14.5,
        tuition_fee_min: 14000000,
        tuition_fee_max: 22000000,
        currency: 'VND',
        admission_requirements: ['Tốt nghiệp THPT', 'Điểm thi THPT Quốc gia'],
        scholarships: ['Học bổng tài năng', 'Học bổng nghiên cứu'],
        international_partnerships: ['Harvard', 'Oxford', 'Tokyo University'],
        campus_map_url: 'https://maps.google.com/?q=10.7629,106.6602',
        latitude: 10.7629,
        longitude: 106.6602,
        is_featured: true,
        is_verified: true,
        view_count: 14000,
        review_count: 1100,
        average_rating: 4.2,
        total_rating: 4620,
      },
      {
        name: 'Đại học FPT',
        short_name: 'FPT',
        english_name: 'FPT University',
        address: 'Lô E2a-7, Đường D1, Khu Công nghệ cao, TP.HCM',
        city: 'TP.HCM',
        province: 'TP.HCM',
        location: ['TP.HCM'],
        phone: '028 7300 1866',
        email: 'contact@fpt.edu.vn',
        website: 'https://fpt.edu.vn',
        facebook: 'https://www.facebook.com/fptuniversity',
        logo_url: 'https://example.com/fpt-logo.png',
        banner_url: 'https://example.com/fpt-banner.png',
        description: 'Đại học FPT là trường đại học tư thục hàng đầu về công nghệ thông tin.',
        history: 'Được thành lập năm 2006, FPT University có lịch sử hơn 15 năm phát triển.',
        mission: 'Đào tạo nguồn nhân lực chất lượng cao trong lĩnh vực công nghệ.',
        vision: 'Trở thành đại học công nghệ hàng đầu Việt Nam.',
        type: UniversityType.PRIVATE,
        status: UniversityStatus.ACTIVE,
        founded_year: 2006,
        accreditation: 'AUN-QA',
        specializations: ['Công nghệ thông tin', 'Kinh tế', 'Ngôn ngữ', 'Truyền thông'],
        facilities: ['Thư viện', 'Phòng lab', 'Ký túc xá', 'Sân thể thao'],
        achievements: ['Top 10 tư thục Việt Nam', 'Đối tác Microsoft'],
        ranking_national: 'Top 10 tư thục',
        ranking_international: 'Top 5000',
        student_count: 25000,
        faculty_count: 800,
        acceptance_rate: 25.0,
        tuition_fee_min: 25000000,
        tuition_fee_max: 35000000,
        currency: 'VND',
        admission_requirements: ['Tốt nghiệp THPT', 'Phỏng vấn', 'Bài test'],
        scholarships: ['Học bổng tài năng', 'Học bổng khuyến khích'],
        international_partnerships: ['Microsoft', 'IBM', 'Samsung'],
        campus_map_url: 'https://maps.google.com/?q=10.8413,106.8098',
        latitude: 10.8413,
        longitude: 106.8098,
        is_featured: true,
        is_verified: true,
        view_count: 8000,
        review_count: 650,
        average_rating: 4.0,
        total_rating: 2600,
      },
    ];

    for (const university of universities) {
      const existingUniversity = await universityRepository.findOne({
        where: { name: university.name },
      });

      if (!existingUniversity) {
        await universityRepository.save(university);
        console.log(`✅ Created university: ${university.name}`);
      }
    }
  }
} 