import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1755225455692 implements MigrationInterface {
    name = 'InitialMigration1755225455692'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_profiles_gender_enum" AS ENUM('male', 'female', 'other', 'prefer_not_to_say')`);
        await queryRunner.query(`CREATE TABLE "user_profiles" ("id" SERIAL NOT NULL, "userId" bigint NOT NULL, "firstName" character varying(100), "lastName" character varying(100), "displayName" character varying(150), "avatarUrl" character varying(500), "coverImageUrl" character varying(500), "bio" text, "dateOfBirth" date, "gender" "public"."user_profiles_gender_enum", "country" character varying(100), "city" character varying(100), "address" text, "timezone" character varying(50) NOT NULL DEFAULT 'UTC', "language" character varying(10) NOT NULL DEFAULT 'vi', "universityName" character varying(255), "major" character varying(255), "graduationYear" integer, "studentId" character varying(50), "isStudentVerified" boolean NOT NULL DEFAULT false, "privacySettings" json, "notificationSettings" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "REL_6ca9503d77ae39b4b5a6cc3ba8" UNIQUE ("user_id"), CONSTRAINT "PK_1ec6662219f4605723f1e41b6cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" SERIAL NOT NULL, "userId" bigint NOT NULL, "sessionToken" character varying(1000) NOT NULL, "refreshToken" character varying(1000), "deviceId" character varying(255), "ipAddress" character varying(45), "userAgent" text, "location" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "lastActivityAt" TIMESTAMP NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "UQ_cd183bcb9ffe40bd858ed6b6b87" UNIQUE ("sessionToken"), CONSTRAINT "UQ_56ca06637d897e5d0b970ef5255" UNIQUE ("refreshToken"), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_devices_devicetype_enum" AS ENUM('web', 'mobile', 'tablet', 'desktop')`);
        await queryRunner.query(`CREATE TABLE "user_devices" ("id" SERIAL NOT NULL, "userId" bigint NOT NULL, "deviceId" character varying(255) NOT NULL, "deviceName" character varying(255), "deviceType" "public"."user_devices_devicetype_enum" NOT NULL, "platform" character varying(50), "browser" character varying(100), "isTrusted" boolean NOT NULL DEFAULT false, "pushToken" character varying(500), "lastUsedAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "UQ_e81c41e04269a2d2152f0d60b5c" UNIQUE ("deviceId"), CONSTRAINT "PK_c9e7e648903a9e537347aba4371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "resource" character varying(100) NOT NULL, "action" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "isSystem" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_activities_activitytype_enum" AS ENUM('profile_created', 'profile_updated', 'profile_deleted', 'avatar_uploaded', 'avatar_deleted', 'account_deactivated', 'account_deleted', 'account_reactivated', 'login_success', 'login_failed', 'logout', 'password_changed', 'password_reset_requested', 'password_reset_completed', 'email_verified', 'email_verification_sent', 'two_factor_enabled', 'two_factor_disabled', 'suspicious_activity_detected', 'review_submitted', 'review_updated', 'review_deleted', 'review_liked', 'review_unliked', 'review_reported', 'blog_created', 'blog_updated', 'blog_deleted', 'blog_published', 'blog_moderated', 'blog_liked', 'blog_unliked', 'blog_viewed', 'tag_created', 'tag_updated', 'tag_deleted', 'tag_assigned', 'tag_removed', 'upload_image', 'update_image', 'delete_image')`);
        await queryRunner.query(`CREATE TABLE "user_activities" ("id" SERIAL NOT NULL, "userId" bigint, "activityType" "public"."user_activities_activitytype_enum" NOT NULL, "description" text NOT NULL, "metadata" json, "ipAddress" character varying(45), "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_1245d4d2cf04ba7743f2924d951" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(100), "color" character varying(7), "isActive" boolean NOT NULL DEFAULT true, "usageCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blog_likes" ("id" SERIAL NOT NULL, "userId" bigint NOT NULL, "blogId" bigint NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, "blog_id" integer, CONSTRAINT "UQ_562b29e40a6f7c4ebc3e4f5feaf" UNIQUE ("userId", "blogId"), CONSTRAINT "PK_92ed5e155b9560753110e73c11f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."blogs_category_enum" AS ENUM('news', 'guide', 'review', 'interview', 'opinion', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."blogs_status_enum" AS ENUM('draft', 'published', 'approved', 'rejected', 'banned')`);
        await queryRunner.query(`CREATE TABLE "blogs" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "excerpt" character varying(500), "featuredImage" character varying(500), "category" "public"."blogs_category_enum" NOT NULL DEFAULT 'other', "status" "public"."blogs_status_enum" NOT NULL DEFAULT 'draft', "moderationReason" text, "viewCount" integer NOT NULL DEFAULT '0', "likeCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "publishedAt" TIMESTAMP, "moderatedAt" TIMESTAMP, "authorId" integer, "moderatorId" bigint, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "moderator_id" integer, CONSTRAINT "PK_e113335f11c926da929a625f118" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_056d0a36a376bec095df58754f" ON "blogs" ("category", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b61f8a69b92c33fcd7de378857" ON "blogs" ("authorId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecde40494d044f257b88b70c90" ON "blogs" ("status", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended', 'banned', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."users_accounttype_enum" AS ENUM('student', 'university_rep', 'admin', 'moderator', 'super_admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "username" character varying(50) NOT NULL, "email" character varying(255) NOT NULL, "emailVerifiedAt" TIMESTAMP, "passwordHash" character varying(255) NOT NULL, "phone" character varying(20), "phoneVerifiedAt" TIMESTAMP, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "accountType" "public"."users_accounttype_enum" NOT NULL DEFAULT 'student', "isVerified" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP, "lastActivityAt" TIMESTAMP, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP, "isBanned" boolean NOT NULL DEFAULT false, "banReason" character varying(500), "bannedAt" TIMESTAMP, "banExpiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."uploaded_files_status_enum" AS ENUM('active', 'deleted')`);
        await queryRunner.query(`CREATE TABLE "uploaded_files" ("id" SERIAL NOT NULL, "publicId" character varying(255) NOT NULL, "secureUrl" character varying(500) NOT NULL, "url" character varying(500) NOT NULL, "fileName" character varying(100) NOT NULL, "fileType" character varying(50) NOT NULL, "fileSize" bigint NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "format" character varying(20) NOT NULL, "folder" character varying(100) NOT NULL DEFAULT 'edu-review-hub', "status" "public"."uploaded_files_status_enum" NOT NULL DEFAULT 'active', "userId" bigint NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_e2d47e01bd5be386bf0067b2ed8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."universities_type_enum" AS ENUM('public', 'private', 'international', 'college')`);
        await queryRunner.query(`CREATE TYPE "public"."universities_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "universities" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "short_name" character varying(100), "english_name" character varying(255), "address" character varying(500), "location" text, "city" character varying(100), "province" character varying(100), "phone" character varying(20), "email" character varying(255), "website" character varying(500), "facebook" character varying(500), "logo_url" character varying(500), "banner_url" character varying(500), "description" text, "history" text, "mission" text, "vision" text, "type" "public"."universities_type_enum" NOT NULL DEFAULT 'public', "status" "public"."universities_status_enum" NOT NULL DEFAULT 'active', "founded_year" integer, "accreditation" character varying(100), "specializations" text, "facilities" text, "achievements" text, "ranking_national" character varying(100), "ranking_international" character varying(100), "student_count" integer, "faculty_count" integer, "acceptance_rate" numeric(5,2), "tuition_fee_min" numeric(10,2), "tuition_fee_max" numeric(10,2), "currency" character varying(20), "admission_requirements" text, "scholarships" text, "international_partnerships" text, "campus_map_url" character varying(500), "latitude" numeric(10,6), "longitude" numeric(10,6), "is_featured" boolean NOT NULL DEFAULT false, "is_verified" boolean NOT NULL DEFAULT false, "view_count" integer NOT NULL DEFAULT '0', "review_count" integer NOT NULL DEFAULT '0', "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "total_rating" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8da52f2cee6b407559fdbabf59e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14ed1feb539f49b699b96cb47e" ON "universities" ("location", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_564bd25fac259b188483f417f8" ON "universities" ("type", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_25b08a78732a663bb35872eaa7" ON "universities" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."university_review_criteria_type_enum" AS ENUM('academic', 'facility', 'social', 'career', 'overall')`);
        await queryRunner.query(`CREATE TYPE "public"."university_review_criteria_weight_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "university_review_criteria" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "display_name" character varying(255), "description" text, "type" "public"."university_review_criteria_type_enum" NOT NULL DEFAULT 'overall', "weight" "public"."university_review_criteria_weight_enum" NOT NULL DEFAULT '2', "max_score" integer NOT NULL DEFAULT '5', "is_active" boolean NOT NULL DEFAULT true, "is_required" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "icon" character varying(100), "color" character varying(7), CONSTRAINT "UQ_b33f7ec6623a3fcfd703b8850b5" UNIQUE ("name"), CONSTRAINT "PK_68b4606c549726fcb9d617fdb88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "university_review_scores" ("id" SERIAL NOT NULL, "score" integer NOT NULL, "review_id" integer NOT NULL, "criterion_id" integer NOT NULL, CONSTRAINT "PK_1e6d8a9550d999f32c79771fd81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."university_reviews_status_enum" AS ENUM('pending', 'approved', 'rejected', 'hidden')`);
        await queryRunner.query(`CREATE TYPE "public"."university_reviews_review_type_enum" AS ENUM('student', 'alumni', 'parent', 'visitor', 'staff')`);
        await queryRunner.query(`CREATE TABLE "university_reviews" ("id" SERIAL NOT NULL, "university_id" integer NOT NULL, "user_id" integer NOT NULL, "content" text NOT NULL, "pros" text, "cons" text, "recommendation" text, "overall_score" double precision NOT NULL, "status" "public"."university_reviews_status_enum" NOT NULL DEFAULT 'pending', "review_type" "public"."university_reviews_review_type_enum" NOT NULL DEFAULT 'student', "study_program" character varying(100), "study_year" integer, "graduation_year" integer, "is_anonymous" boolean NOT NULL DEFAULT false, "is_verified" boolean NOT NULL DEFAULT false, "is_helpful" boolean NOT NULL DEFAULT false, "helpful_count" integer NOT NULL DEFAULT '0', "report_count" integer NOT NULL DEFAULT '0', "admin_notes" text, "moderator_id" bigint, "moderated_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_74d341c0d5c4b1d3924c96baad6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b2589ce1cc1b70f8ea409478b" ON "university_reviews" ("overall_score", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_6383890e73c51506d6b824a5fc" ON "university_reviews" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_25f6fb1d3940c4ebca648b2a25" ON "university_reviews" ("university_id", "status") `);
        await queryRunner.query(`CREATE TABLE "security_logs" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_48ce9a9a3215af82611525ce08b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" SERIAL NOT NULL, "refresh_token" character varying NOT NULL, "device_id" character varying, "ip_address" character varying, "user_agent" character varying, "is_active" boolean NOT NULL DEFAULT true, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recommendations" ("id" SERIAL NOT NULL, "personality_type" character varying, "interests" text, "academic_score" double precision, "recommended_universities" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_23a8d2db26db8cabb6ae9d6cd87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_resets" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "token" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, "ip_address" character varying, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4816377aa98211c1de34469e742" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chats" ("id" SERIAL NOT NULL, "session_id" character varying NOT NULL, "is_anonymous" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" SERIAL NOT NULL, "sender" character varying NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "chat_id" integer NOT NULL, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "embedded_websites" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "status" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_16c6a62bf62aed40132279ffa79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."email_verifications_type_enum" AS ENUM('email_verification', 'password_reset', 'email_change')`);
        await queryRunner.query(`CREATE TYPE "public"."email_verifications_status_enum" AS ENUM('pending', 'verified', 'expired', 'used')`);
        await queryRunner.query(`CREATE TABLE "email_verifications" ("id" SERIAL NOT NULL, "userId" bigint NOT NULL, "email" character varying(255) NOT NULL, "type" "public"."email_verifications_type_enum" NOT NULL, "status" "public"."email_verifications_status_enum" NOT NULL DEFAULT 'pending', "expiresAt" TIMESTAMP NOT NULL, "verifiedAt" TIMESTAMP, "ipAddress" character varying(45), "userAgent" text, "otp" character varying(10), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "UQ_77f35b4955bc8cc74da06ca6ffe" UNIQUE ("otp"), CONSTRAINT "PK_c1ea2921e767f83cd44c0af203f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chatbot_blacklist" ("id" SERIAL NOT NULL, "reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_adf454d361a54101250de6ea436" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."account_deactivations_type_enum" AS ENUM('deactivate', 'delete', 'reactivate')`);
        await queryRunner.query(`CREATE TYPE "public"."account_deactivations_status_enum" AS ENUM('pending', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "account_deactivations" ("id" SERIAL NOT NULL, "userId" bigint NOT NULL, "type" "public"."account_deactivations_type_enum" NOT NULL, "status" "public"."account_deactivations_status_enum" NOT NULL DEFAULT 'pending', "reason" text, "deactivatedAt" TIMESTAMP, "reactivatedAt" TIMESTAMP, "scheduledDeletionAt" TIMESTAMP, "isPermanent" boolean NOT NULL DEFAULT false, "ipAddress" character varying(45), "userAgent" text, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_6aaecd2a6683ccf7af00e769849" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blog_tags" ("tag_id" integer NOT NULL, "blog_id" integer NOT NULL, CONSTRAINT "PK_561e9296a2ba753a9900831104c" PRIMARY KEY ("tag_id", "blog_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d8cc813269fa2a0ec3f857187" ON "blog_tags" ("tag_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_20ce3565a4dda1ce7a3e8104f2" ON "blog_tags" ("blog_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_devices" ADD CONSTRAINT "FK_28bd79e1b3f7c1168f0904ce241" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_activities" ADD CONSTRAINT "FK_a283f37e08edf5e37d38b375eec" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog_likes" ADD CONSTRAINT "FK_2d57b6a07242ebf8b22d0702cb8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog_likes" ADD CONSTRAINT "FK_bc3c053e964f753dd07f339db35" FOREIGN KEY ("blog_id") REFERENCES "blogs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_05aa4239904d894452e339e5139" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_0d57d4c1dfbcb2980d40bd51da3" FOREIGN KEY ("moderator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uploaded_files" ADD CONSTRAINT "FK_dbd75c6a10be3314708a397da86" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "university_review_scores" ADD CONSTRAINT "FK_fc79bd8799cbb16d813829fe3f6" FOREIGN KEY ("review_id") REFERENCES "university_reviews"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "university_review_scores" ADD CONSTRAINT "FK_dd1a2fe2218847d571533d126e5" FOREIGN KEY ("criterion_id") REFERENCES "university_review_criteria"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "university_reviews" ADD CONSTRAINT "FK_693fcdb9240767ed83ad8e86163" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "university_reviews" ADD CONSTRAINT "FK_7c44f4022a6b2abb90b97eb55d4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_logs" ADD CONSTRAINT "FK_3fc41b4fda367506672e9030ad0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recommendations" ADD CONSTRAINT "FK_36a0fe63642889bc60ceebce002" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_b6c92d818d42e3e298e84d94414" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_7540635fef1922f0b156b9ef74f" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embedded_websites" ADD CONSTRAINT "FK_cd5d8b9aed449eefd94438b8482" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verifications" ADD CONSTRAINT "FK_c4f1838323ae1dff5aa00148915" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatbot_blacklist" ADD CONSTRAINT "FK_10eb235367fd200d8e7c2a461d8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_deactivations" ADD CONSTRAINT "FK_95fbb1c473d68acccd4da30a6d3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog_tags" ADD CONSTRAINT "FK_7d8cc813269fa2a0ec3f8571876" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "blog_tags" ADD CONSTRAINT "FK_20ce3565a4dda1ce7a3e8104f2a" FOREIGN KEY ("blog_id") REFERENCES "blogs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "blog_tags" DROP CONSTRAINT "FK_20ce3565a4dda1ce7a3e8104f2a"`);
        await queryRunner.query(`ALTER TABLE "blog_tags" DROP CONSTRAINT "FK_7d8cc813269fa2a0ec3f8571876"`);
        await queryRunner.query(`ALTER TABLE "account_deactivations" DROP CONSTRAINT "FK_95fbb1c473d68acccd4da30a6d3"`);
        await queryRunner.query(`ALTER TABLE "chatbot_blacklist" DROP CONSTRAINT "FK_10eb235367fd200d8e7c2a461d8"`);
        await queryRunner.query(`ALTER TABLE "email_verifications" DROP CONSTRAINT "FK_c4f1838323ae1dff5aa00148915"`);
        await queryRunner.query(`ALTER TABLE "embedded_websites" DROP CONSTRAINT "FK_cd5d8b9aed449eefd94438b8482"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_7540635fef1922f0b156b9ef74f"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_b6c92d818d42e3e298e84d94414"`);
        await queryRunner.query(`ALTER TABLE "recommendations" DROP CONSTRAINT "FK_36a0fe63642889bc60ceebce002"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "security_logs" DROP CONSTRAINT "FK_3fc41b4fda367506672e9030ad0"`);
        await queryRunner.query(`ALTER TABLE "university_reviews" DROP CONSTRAINT "FK_7c44f4022a6b2abb90b97eb55d4"`);
        await queryRunner.query(`ALTER TABLE "university_reviews" DROP CONSTRAINT "FK_693fcdb9240767ed83ad8e86163"`);
        await queryRunner.query(`ALTER TABLE "university_review_scores" DROP CONSTRAINT "FK_dd1a2fe2218847d571533d126e5"`);
        await queryRunner.query(`ALTER TABLE "university_review_scores" DROP CONSTRAINT "FK_fc79bd8799cbb16d813829fe3f6"`);
        await queryRunner.query(`ALTER TABLE "uploaded_files" DROP CONSTRAINT "FK_dbd75c6a10be3314708a397da86"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_0d57d4c1dfbcb2980d40bd51da3"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_05aa4239904d894452e339e5139"`);
        await queryRunner.query(`ALTER TABLE "blog_likes" DROP CONSTRAINT "FK_bc3c053e964f753dd07f339db35"`);
        await queryRunner.query(`ALTER TABLE "blog_likes" DROP CONSTRAINT "FK_2d57b6a07242ebf8b22d0702cb8"`);
        await queryRunner.query(`ALTER TABLE "user_activities" DROP CONSTRAINT "FK_a283f37e08edf5e37d38b375eec"`);
        await queryRunner.query(`ALTER TABLE "user_devices" DROP CONSTRAINT "FK_28bd79e1b3f7c1168f0904ce241"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20ce3565a4dda1ce7a3e8104f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d8cc813269fa2a0ec3f857187"`);
        await queryRunner.query(`DROP TABLE "blog_tags"`);
        await queryRunner.query(`DROP TABLE "account_deactivations"`);
        await queryRunner.query(`DROP TYPE "public"."account_deactivations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."account_deactivations_type_enum"`);
        await queryRunner.query(`DROP TABLE "chatbot_blacklist"`);
        await queryRunner.query(`DROP TABLE "email_verifications"`);
        await queryRunner.query(`DROP TYPE "public"."email_verifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."email_verifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "embedded_websites"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP TABLE "password_resets"`);
        await queryRunner.query(`DROP TABLE "recommendations"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "security_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25f6fb1d3940c4ebca648b2a25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6383890e73c51506d6b824a5fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b2589ce1cc1b70f8ea409478b"`);
        await queryRunner.query(`DROP TABLE "university_reviews"`);
        await queryRunner.query(`DROP TYPE "public"."university_reviews_review_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."university_reviews_status_enum"`);
        await queryRunner.query(`DROP TABLE "university_review_scores"`);
        await queryRunner.query(`DROP TABLE "university_review_criteria"`);
        await queryRunner.query(`DROP TYPE "public"."university_review_criteria_weight_enum"`);
        await queryRunner.query(`DROP TYPE "public"."university_review_criteria_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25b08a78732a663bb35872eaa7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_564bd25fac259b188483f417f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14ed1feb539f49b699b96cb47e"`);
        await queryRunner.query(`DROP TABLE "universities"`);
        await queryRunner.query(`DROP TYPE "public"."universities_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."universities_type_enum"`);
        await queryRunner.query(`DROP TABLE "uploaded_files"`);
        await queryRunner.query(`DROP TYPE "public"."uploaded_files_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_accounttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecde40494d044f257b88b70c90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b61f8a69b92c33fcd7de378857"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_056d0a36a376bec095df58754f"`);
        await queryRunner.query(`DROP TABLE "blogs"`);
        await queryRunner.query(`DROP TYPE "public"."blogs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."blogs_category_enum"`);
        await queryRunner.query(`DROP TABLE "blog_likes"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "user_activities"`);
        await queryRunner.query(`DROP TYPE "public"."user_activities_activitytype_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "user_devices"`);
        await queryRunner.query(`DROP TYPE "public"."user_devices_devicetype_enum"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
        await queryRunner.query(`DROP TABLE "user_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."user_profiles_gender_enum"`);
    }

}
